const List<Map<String, dynamic>> INDIAN_FOOD_ITEMS = [
  // BREAKFAST (15 items)
  {
    'name': 'Masala Dosa',
    'category': 'Breakfast',
    'price': 50,
    'description': 'Crispy rice crepe filled with spiced potato masala',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'wednesday', 'friday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1694809430138-eb5e6d00a44e?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Idli Sambar',
    'category': 'Breakfast',
    'price': 40,
    'description': 'Steamed rice cakes served with lentil curry',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1630409346730-1ddc6bb3c0e4?w=400',
    'preparationTime': 10,
  },
  {
    'name': 'Poha',
    'category': 'Breakfast',
    'price': 30,
    'description': 'Flattened rice with peanuts and spices',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1645696261268-1b77a6c47c2e?w=400',
    'preparationTime': 12,
  },
  {
    'name': 'Upma',
    'category': 'Breakfast',
    'price': 35,
    'description': 'Semolina porridge with vegetables',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1626673344990-4dbced5e2b4f?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Aloo Paratha',
    'category': 'Breakfast',
    'price': 45,
    'description': 'Whole wheat flatbread stuffed with spiced potatoes',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1644704029796-07dd37430e9c?w=400',
    'preparationTime': 20,
  },
  {
    'name': 'Medu Vada',
    'category': 'Breakfast',
    'price': 35,
    'description': 'Crispy lentil donuts with sambar',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1626776876729-bab4eb6f9a3a?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Pongal',
    'category': 'Breakfast',
    'price': 40,
    'description': 'Rice and lentil porridge with ghee',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    'preparationTime': 20,
  },
  {
    'name': 'Uttapam',
    'category': 'Breakfast',
    'price': 55,
    'description': 'Thick rice pancake with vegetables',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Rava Dosa',
    'category': 'Breakfast',
    'price': 50,
    'description': 'Crispy semolina crepe with spices',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Sabudana Khichdi',
    'category': 'Breakfast',
    'price': 40,
    'description': 'Tapioca pearls with peanuts and spices',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Misal Pav',
    'category': 'Breakfast',
    'price': 50,
    'description': 'Spicy sprouts curry with bread',
    'isVeg': true,
    'spiceLevel': 'high',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    'preparationTime': 20,
  },
  {
    'name': 'Rava Idli',
    'category': 'Breakfast',
    'price': 35,
    'description': 'Steamed semolina cakes with chutney',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1630409346730-1ddc6bb3c0e4?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Pesarattu',
    'category': 'Breakfast',
    'price': 45,
    'description': 'Green gram dosa with upma filling',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=400',
    'preparationTime': 18,
  },
  {
    'name': 'Appam',
    'category': 'Breakfast',
    'price': 40,
    'description': 'Soft rice pancakes with coconut milk',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Puttu',
    'category': 'Breakfast',
    'price': 40,
    'description': 'Steamed rice flour with coconut',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    'preparationTime': 20,
  },

  // RICE (15 items)
  {
    'name': 'Veg Biryani',
    'category': 'Rice',
    'price': 80,
    'description': 'Fragrant basmati rice with mixed vegetables',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'wednesday', 'friday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=400',
    'preparationTime': 25,
  },
  {
    'name': 'Chicken Biryani',
    'category': 'Rice',
    'price': 120,
    'description': 'Aromatic rice with tender chicken',
    'isVeg': false,
    'spiceLevel': 'high',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
    'preparationTime': 30,
  },
  {
    'name': 'Curd Rice',
    'category': 'Rice',
    'price': 40,
    'description': 'Cooling rice with yogurt and tempering',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
    'preparationTime': 10,
  },
  {
    'name': 'Lemon Rice',
    'category': 'Rice',
    'price': 45,
    'description': 'Tangy rice with curry leaves',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Jeera Rice',
    'category': 'Rice',
    'price': 50,
    'description': 'Fragrant basmati rice with cumin',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Mutton Biryani',
    'category': 'Rice',
    'price': 150,
    'description': 'Rich aromatic rice with tender mutton',
    'isVeg': false,
    'spiceLevel': 'high',
    'availableDays': ['wednesday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
    'preparationTime': 35,
  },
  {
    'name': 'Egg Fried Rice',
    'category': 'Rice',
    'price': 70,
    'description': 'Wok-tossed rice with scrambled eggs',
    'isVeg': false,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Tamarind Rice',
    'category': 'Rice',
    'price': 45,
    'description': 'Tangy rice with tamarind and peanuts',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Tomato Rice',
    'category': 'Rice',
    'price': 50,
    'description': 'Flavorful rice with tomato and spices',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Coconut Rice',
    'category': 'Rice',
    'price': 50,
    'description': 'Aromatic rice with fresh coconut',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Kashmiri Pulao',
    'category': 'Rice',
    'price': 90,
    'description': 'Sweet and savory rice with dry fruits',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['wednesday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=400',
    'preparationTime': 25,
  },
  {
    'name': 'Hyderabadi Biryani',
    'category': 'Rice',
    'price': 130,
    'description': 'Authentic dum-cooked chicken biryani',
    'isVeg': false,
    'spiceLevel': 'high',
    'availableDays': ['thursday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
    'preparationTime': 35,
  },
  {
    'name': 'Prawns Biryani',
    'category': 'Rice',
    'price': 160,
    'description': 'Aromatic rice with succulent prawns',
    'isVeg': false,
    'spiceLevel': 'high',
    'availableDays': ['friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
    'preparationTime': 30,
  },
  {
    'name': 'Mint Rice',
    'category': 'Rice',
    'price': 55,
    'description': 'Refreshing rice with fresh mint',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Paneer Biryani',
    'category': 'Rice',
    'price': 110,
    'description': 'Aromatic rice with cottage cheese',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=400',
    'preparationTime': 25,
  },

  // CURRY (15 items)
  {
    'name': 'Paneer Butter Masala',
    'category': 'Curry',
    'price': 100,
    'description': 'Cottage cheese in rich tomato gravy',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400',
    'preparationTime': 20,
  },
  {
    'name': 'Dal Tadka',
    'category': 'Curry',
    'price': 60,
    'description': 'Yellow lentils with aromatic tempering',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
    'preparationTime': 25,
  },
  {
    'name': 'Chole Masala',
    'category': 'Curry',
    'price': 70,
    'description': 'Spiced chickpea curry',
    'isVeg': true,
    'spiceLevel': 'high',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    'preparationTime': 20,
  },
  {
    'name': 'Rajma Masala',
    'category': 'Curry',
    'price': 65,
    'description': 'Red kidney beans in thick gravy',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    'preparationTime': 25,
  },
  {
    'name': 'Palak Paneer',
    'category': 'Curry',
    'price': 90,
    'description': 'Cottage cheese in creamy spinach',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    'preparationTime': 20,
  },
  {
    'name': 'Butter Chicken',
    'category': 'Curry',
    'price': 140,
    'description': 'Tender chicken in buttery tomato sauce',
    'isVeg': false,
    'spiceLevel': 'medium',
    'availableDays': ['wednesday', 'friday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
    'preparationTime': 30,
  },
  {
    'name': 'Kadai Paneer',
    'category': 'Curry',
    'price': 95,
    'description': 'Cottage cheese with bell peppers in spicy gravy',
    'isVeg': true,
    'spiceLevel': 'high',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400',
    'preparationTime': 20,
  },
  {
    'name': 'Chicken Curry',
    'category': 'Curry',
    'price': 120,
    'description': 'Traditional chicken curry with spices',
    'isVeg': false,
    'spiceLevel': 'high',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
    'preparationTime': 30,
  },
  {
    'name': 'Dal Makhani',
    'category': 'Curry',
    'price': 80,
    'description': 'Black lentils in creamy tomato gravy',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
    'preparationTime': 30,
  },
  {
    'name': 'Malai Kofta',
    'category': 'Curry',
    'price': 110,
    'description': 'Vegetable dumplings in creamy sauce',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['wednesday', 'friday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400',
    'preparationTime': 25,
  },
  {
    'name': 'Mutton Rogan Josh',
    'category': 'Curry',
    'price': 160,
    'description': 'Aromatic Kashmiri mutton curry',
    'isVeg': false,
    'spiceLevel': 'high',
    'availableDays': ['thursday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
    'preparationTime': 35,
  },
  {
    'name': 'Egg Curry',
    'category': 'Curry',
    'price': 70,
    'description': 'Boiled eggs in spiced tomato gravy',
    'isVeg': false,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
    'preparationTime': 20,
  },
  {
    'name': 'Bhindi Masala',
    'category': 'Curry',
    'price': 70,
    'description': 'Spiced okra stir-fry',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    'preparationTime': 20,
  },
  {
    'name': 'Aloo Gobi',
    'category': 'Curry',
    'price': 65,
    'description': 'Potato and cauliflower curry',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    'preparationTime': 20,
  },
  {
    'name': 'Fish Curry',
    'category': 'Curry',
    'price': 130,
    'description': 'Fresh fish in tangy tomato gravy',
    'isVeg': false,
    'spiceLevel': 'high',
    'availableDays': ['wednesday', 'friday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
    'preparationTime': 25,
  },

  // BREAD (10 items)
  {
    'name': 'Roti',
    'category': 'Bread',
    'price': 10,
    'description': 'Whole wheat Indian flatbread',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1619870940850-7d2b9d155f87?w=400',
    'preparationTime': 5,
  },
  {
    'name': 'Naan',
    'category': 'Bread',
    'price': 20,
    'description': 'Soft leavened flatbread',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400',
    'preparationTime': 10,
  },
  {
    'name': 'Butter Naan',
    'category': 'Bread',
    'price': 25,
    'description': 'Soft naan brushed with butter',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400',
    'preparationTime': 10,
  },
  {
    'name': 'Garlic Naan',
    'category': 'Bread',
    'price': 30,
    'description': 'Naan topped with garlic and butter',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400',
    'preparationTime': 12,
  },
  {
    'name': 'Paratha',
    'category': 'Bread',
    'price': 20,
    'description': 'Layered whole wheat flatbread',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1612564148954-59545876eaa0?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Kulcha',
    'category': 'Bread',
    'price': 25,
    'description': 'Soft leavened bread stuffed with spices',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Puri',
    'category': 'Bread',
    'price': 15,
    'description': 'Deep fried puffed bread',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'wednesday', 'friday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1619870940850-7d2b9d155f87?w=400',
    'preparationTime': 10,
  },
  {
    'name': 'Bhatura',
    'category': 'Bread',
    'price': 20,
    'description': 'Fluffy deep fried leavened bread',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1619870940850-7d2b9d155f87?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Roomali Roti',
    'category': 'Bread',
    'price': 15,
    'description': 'Thin handkerchief-like bread',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['wednesday', 'friday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1619870940850-7d2b9d155f87?w=400',
    'preparationTime': 10,
  },
  {
    'name': 'Tandoori Roti',
    'category': 'Bread',
    'price': 12,
    'description': 'Whole wheat bread from tandoor',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1619870940850-7d2b9d155f87?w=400',
    'preparationTime': 8,
  },

  // SNACKS (15 items)
  {
    'name': 'Samosa',
    'category': 'Snacks',
    'price': 20,
    'description': 'Crispy pastry with spiced potato filling',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    'preparationTime': 5,
  },
  {
    'name': 'Pakora',
    'category': 'Snacks',
    'price': 30,
    'description': 'Mixed vegetable fritters',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    'preparationTime': 10,
  },
  {
    'name': 'Vada Pav',
    'category': 'Snacks',
    'price': 25,
    'description': 'Spiced potato fritter in bun',
    'isVeg': true,
    'spiceLevel': 'high',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1626074353765-517a90bc5dcc?w=400',
    'preparationTime': 8,
  },
  {
    'name': 'Pani Puri',
    'category': 'Snacks',
    'price': 30,
    'description': 'Crispy puris with tangy water',
    'isVeg': true,
    'spiceLevel': 'high',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    'preparationTime': 10,
  },
  {
    'name': 'Bread Pakora',
    'category': 'Snacks',
    'price': 25,
    'description': 'Bread slices in gram flour batter',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    'preparationTime': 12,
  },
  {
    'name': 'Kachori',
    'category': 'Snacks',
    'price': 20,
    'description': 'Deep fried pastry with lentil filling',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    'preparationTime': 10,
  },
  {
    'name': 'Aloo Tikki',
    'category': 'Snacks',
    'price': 30,
    'description': 'Spiced potato patties with chutneys',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'wednesday', 'friday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Dhokla',
    'category': 'Snacks',
    'price': 35,
    'description': 'Steamed gram flour cake',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    'preparationTime': 20,
  },
  {
    'name': 'Paneer Tikka',
    'category': 'Snacks',
    'price': 90,
    'description': 'Grilled cottage cheese cubes',
    'isVeg': true,
    'spiceLevel': 'high',
    'availableDays': ['wednesday', 'friday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400',
    'preparationTime': 20,
  },
  {
    'name': 'Chicken Tikka',
    'category': 'Snacks',
    'price': 110,
    'description': 'Grilled spiced chicken pieces',
    'isVeg': false,
    'spiceLevel': 'high',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
    'preparationTime': 25,
  },
  {
    'name': 'Spring Roll',
    'category': 'Snacks',
    'price': 40,
    'description': 'Crispy rolls with vegetable filling',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1626074353765-517a90bc5dcc?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Chicken Wings',
    'category': 'Snacks',
    'price': 120,
    'description': 'Spicy fried chicken wings',
    'isVeg': false,
    'spiceLevel': 'high',
    'availableDays': ['thursday', 'friday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
    'preparationTime': 20,
  },
  {
    'name': 'French Fries',
    'category': 'Snacks',
    'price': 40,
    'description': 'Crispy golden potato fries',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1576107232684-1279f390859f?w=400',
    'preparationTime': 10,
  },
  {
    'name': 'Cheese Balls',
    'category': 'Snacks',
    'price': 50,
    'description': 'Deep fried cheesy balls',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1626074353765-517a90bc5dcc?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Corn Chaat',
    'category': 'Snacks',
    'price': 35,
    'description': 'Spicy sweet corn mixture',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'wednesday', 'friday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    'preparationTime': 10,
  },

  // BEVERAGES (10 items)
  {
    'name': 'Masala Chai',
    'category': 'Beverages',
    'price': 15,
    'description': 'Indian spiced milk tea',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1597318112274-6f0d452de9c8?w=400',
    'preparationTime': 5,
  },
  {
    'name': 'Filter Coffee',
    'category': 'Beverages',
    'price': 20,
    'description': 'South Indian strong coffee',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400',
    'preparationTime': 5,
  },
  {
    'name': 'Lassi',
    'category': 'Beverages',
    'price': 30,
    'description': 'Sweet yogurt drink',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400',
    'preparationTime': 5,
  },
  {
    'name': 'Mango Lassi',
    'category': 'Beverages',
    'price': 40,
    'description': 'Creamy mango yogurt drink',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400',
    'preparationTime': 5,
  },
  {
    'name': 'Buttermilk',
    'category': 'Beverages',
    'price': 20,
    'description': 'Spiced yogurt drink',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400',
    'preparationTime': 5,
  },
  {
    'name': 'Lemon Juice',
    'category': 'Beverages',
    'price': 25,
    'description': 'Fresh lemon juice',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1587486936321-e4c1e5d0d2e9?w=400',
    'preparationTime': 3,
  },
  {
    'name': 'Cold Coffee',
    'category': 'Beverages',
    'price': 40,
    'description': 'Chilled coffee with ice cream',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400',
    'preparationTime': 5,
  },
  {
    'name': 'Badam Milk',
    'category': 'Beverages',
    'price': 35,
    'description': 'Almond flavored milk',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400',
    'preparationTime': 5,
  },
  {
    'name': 'Fresh Lime Soda',
    'category': 'Beverages',
    'price': 25,
    'description': 'Fizzy lime drink',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1587486936321-e4c1e5d0d2e9?w=400',
    'preparationTime': 3,
  },
  {
    'name': 'Jaljeera',
    'category': 'Beverages',
    'price': 20,
    'description': 'Tangy cumin water drink',
    'isVeg': true,
    'spiceLevel': 'mild',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1587486936321-e4c1e5d0d2e9?w=400',
    'preparationTime': 5,
  },

  // DESSERTS (10 items)
  {
    'name': 'Gulab Jamun',
    'category': 'Desserts',
    'price': 25,
    'description': 'Sweet milk dumplings in syrup',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606471191009-63d0929e9d0e?w=400',
    'preparationTime': 5,
  },
  {
    'name': 'Rasgulla',
    'category': 'Desserts',
    'price': 30,
    'description': 'Soft cottage cheese balls in syrup',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606471191009-63d0929e9d0e?w=400',
    'preparationTime': 5,
  },
  {
    'name': 'Kheer',
    'category': 'Desserts',
    'price': 35,
    'description': 'Rice pudding with milk and dry fruits',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'wednesday', 'friday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606471191009-63d0929e9d0e?w=400',
    'preparationTime': 5,
  },
  {
    'name': 'Jalebi',
    'category': 'Desserts',
    'price': 30,
    'description': 'Sweet crispy spirals',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606471191009-63d0929e9d0e?w=400',
    'preparationTime': 5,
  },
  {
    'name': 'Rabri',
    'category': 'Desserts',
    'price': 40,
    'description': 'Sweet condensed milk dessert',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['wednesday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606471191009-63d0929e9d0e?w=400',
    'preparationTime': 5,
  },
  {
    'name': 'Kulfi',
    'category': 'Desserts',
    'price': 35,
    'description': 'Traditional Indian ice cream',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400',
    'preparationTime': 2,
  },
  {
    'name': 'Gajar Halwa',
    'category': 'Desserts',
    'price': 40,
    'description': 'Sweet carrot pudding',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606471191009-63d0929e9d0e?w=400',
    'preparationTime': 5,
  },
  {
    'name': 'Ras Malai',
    'category': 'Desserts',
    'price': 40,
    'description': 'Soft paneer discs in sweet milk',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606471191009-63d0929e9d0e?w=400',
    'preparationTime': 5,
  },
  {
    'name': 'Ice Cream',
    'category': 'Desserts',
    'price': 30,
    'description': 'Assorted flavors',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400',
    'preparationTime': 2,
  },
  {
    'name': 'Shrikhand',
    'category': 'Desserts',
    'price': 35,
    'description': 'Sweetened strained yogurt',
    'isVeg': true,
    'spiceLevel': 'none',
    'availableDays': ['wednesday', 'friday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1606471191009-63d0929e9d0e?w=400',
    'preparationTime': 5,
  },

  // INDO-CHINESE (5 items)
  {
    'name': 'Veg Fried Rice',
    'category': 'Indo-Chinese',
    'price': 70,
    'description': 'Stir fried rice with vegetables',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Chicken Fried Rice',
    'category': 'Indo-Chinese',
    'price': 100,
    'description': 'Stir fried rice with chicken',
    'isVeg': false,
    'spiceLevel': 'medium',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
    'preparationTime': 20,
  },
  {
    'name': 'Chilli Paneer',
    'category': 'Indo-Chinese',
    'price': 90,
    'description': 'Spicy cottage cheese in indo-chinese sauce',
    'isVeg': true,
    'spiceLevel': 'high',
    'availableDays': ['monday', 'wednesday', 'friday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400',
    'preparationTime': 20,
  },
  {
    'name': 'Hakka Noodles',
    'category': 'Indo-Chinese',
    'price': 70,
    'description': 'Stir fried noodles with vegetables',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['tuesday', 'thursday', 'saturday'],
    'imageUrl': 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=400',
    'preparationTime': 15,
  },
  {
    'name': 'Manchurian',
    'category': 'Indo-Chinese',
    'price': 80,
    'description': 'Fried vegetable balls in spicy sauce',
    'isVeg': true,
    'spiceLevel': 'high',
    'availableDays': ['monday', 'wednesday', 'friday'],
    'imageUrl': 'https://images.unsplash.com/photo-1626074353765-517a90bc5dcc?w=400',
    'preparationTime': 20,
  },

  // THALI (5 items)
  {
    'name': 'Mini Thali',
    'category': 'Thali',
    'price': 100,
    'description': '2 Roti, 1 Curry, Rice, Dal, Salad',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    'preparationTime': 20,
  },
  {
    'name': 'Regular Thali',
    'category': 'Thali',
    'price': 130,
    'description': '4 Roti, 2 Curry, Rice, Dal, Sweet, Salad',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    'preparationTime': 25,
  },
  {
    'name': 'Special Thali',
    'category': 'Thali',
    'price': 160,
    'description': '6 Roti, 3 Curry, Rice, Dal, Sweet, Salad, Papad',
    'isVeg': true,
    'spiceLevel': 'medium',
    'availableDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    'preparationTime': 30,
  },
  {
    'name': 'Non-Veg Thali',
    'category': 'Thali',
    'price': 180,
    'description': '4 Roti, 1 Non-veg Curry, 1 Veg Curry, Rice, Dal, Salad',
    'isVeg': false,
    'spiceLevel': 'high',
    'availableDays': ['tuesday', 'thursday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    'preparationTime': 30,
  },
  {
    'name': 'Deluxe Thali',
    'category': 'Thali',
    'price': 220,
    'description': '6 Roti, 4 Curry (1 Non-veg), Rice, Dal, Sweet, Salad, Papad, Dessert',
    'isVeg': false,
    'spiceLevel': 'medium',
    'availableDays': ['friday', 'saturday', 'sunday'],
    'imageUrl': 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    'preparationTime': 35,
  },
];