// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa5CT7Zswe4Jac2UW4DXnv7V_U3ijQdhY',
    appId: '1:515885768543:web:89a60177dd624eca51a0ea',
    messagingSenderId: '515885768543',
    projectId: 'foodasm-mad-project',
    authDomain: 'foodasm-mad-project.firebaseapp.com',
    storageBucket: 'foodasm-mad-project.firebasestorage.app',
    measurementId: 'G-PBLMM2S0BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTypWuSrRzk2JZva_2Mn2zSuARGMXmT_0',
    appId: '1:515885768543:android:f3d63af926a36b3351a0ea',
    messagingSenderId: '515885768543',
    projectId: 'foodasm-mad-project',
    storageBucket: 'foodasm-mad-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUwRbtmz8R21m32LhszQp-odz2CMDDQEI',
    appId: '1:515885768543:ios:4861fa2fbef5047851a0ea',
    messagingSenderId: '515885768543',
    projectId: 'foodasm-mad-project',
    storageBucket: 'foodasm-mad-project.firebasestorage.app',
    iosBundleId: 'com.example.smartCanteen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUwRbtmz8R21m32LhszQp-odz2CMDDQEI',
    appId: '1:515885768543:ios:4861fa2fbef5047851a0ea',
    messagingSenderId: '515885768543',
    projectId: 'foodasm-mad-project',
    storageBucket: 'foodasm-mad-project.firebasestorage.app',
    iosBundleId: 'com.example.smartCanteen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa5CT7Zswe4Jac2UW4DXnv7V_U3ijQdhY',
    appId: '1:515885768543:web:a9e4413264f2984351a0ea',
    messagingSenderId: '515885768543',
    projectId: 'foodasm-mad-project',
    authDomain: 'foodasm-mad-project.firebaseapp.com',
    storageBucket: 'foodasm-mad-project.firebasestorage.app',
    measurementId: 'G-M91RCDMEMF',
  );
}
